In [1]:
import numpy as np

In [3]:
dir(np)



['ALLOW_THREADS',
 'BUFSIZE',
 'CLIP',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'WRAP',
 '_CopyMode',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_builtins',
 '_distributor_init',
 '_financi

In [5]:
x = np.array([33, 1, 2, 3, 4])
print(x)
print(type(x))
print(x.dtype)


[33  1  2  3  4]
<class 'numpy.ndarray'>
int32


In [17]:
x = np.array(["A", 1, 2, 3, 4, 9.2])
print(x)
print(type(x))

['A' '1' '2' '3' '4' '9.2']
<class 'numpy.ndarray'>


In [19]:
print(x.dtype)

<U32


In [21]:
print(x.shape)

(6,)


In [25]:
x = np.array([["A", 1, 2], [3, 4, 9.2]])
print(x)
print(type(x))
print(x.shape)

[['A' '1' '2']
 ['3' '4' '9.2']]
<class 'numpy.ndarray'>
(2, 3)


In [37]:
x = np.array([2, 3, 4, 9])
y = x.reshape(4,1)
print(y)
print(y.shape)

[[2. ]
 [3. ]
 [4. ]
 [9.2]]
(4, 1)


In [47]:
c = np.arange(0,9)
print(c)
type(c)

[0 1 2 3 4 5 6 7 8]


numpy.ndarray

In [55]:
d = np.array([1.234, 3.348, 4.234])
print(d)
np.around(d,2)

[1.234 3.348 4.234]


array([1.23, 3.35, 4.23])

In [63]:
d = np.array([1.234, 3.348, 4.234])
print(np.around(np.sqrt(d),3))

[1.111 1.83  2.058]


In [83]:
a = np.array([[1,2,3], [4,5, np.nan]])
print(a)

[[ 1.  2.  3.]
 [ 4.  5. nan]]


In [67]:
print(a.shape)

(2, 3)


In [71]:
print(a.dtype)

int32


In [87]:
#creating  a 2d array
import numpy as np

a = np.array([[1, 2, 3], [4, 5, np.nan]])
print(a)


[[ 1.  2.  3.]
 [ 4.  5. nan]]


In [85]:
a.dtype

dtype('float64')

In [91]:
#use astype() to convert the datatype
a_copy = a.astype(str)
print(a_copy)
a_copy.dtype

[['1.0' '2.0' '3.0']
 ['4.0' '5.0' 'nan']]


dtype('<U32')

In [97]:
a = np.array([[1,2,3], [4,5,6], [7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [99]:
a.sum(1)

array([ 6, 15, 24])

In [101]:
a.sum(0)

array([12, 15, 18])

In [109]:
print(a.sum(axis = 0))
print(a.sum(axis = 1))


[12 15 18]
[ 6 15 24]


In [117]:
#print mean values
a1 = np.array([[1,2,3], [4,5,6]])
print(a1)
print(a1.sum(axis = 0))
print(a1.sum(axis = 1))

[[1 2 3]
 [4 5 6]]
[5 7 9]
[ 6 15]


In [121]:
#matrix operations
a2 = np.array([[1,2,3], [4,5,6], [7,8,9]])
np.fill_diagonal(a2,0)
print(a2)


[[0 2 3]
 [4 0 6]
 [7 8 0]]


In [127]:
a1 = np.array([[1,2], [5,6]])
a2 = np.array([[6,7], [3,5]])

c = np.matmul(a1, a2)
print(c)

[[12 17]
 [48 65]]


In [133]:
print(a1.T)
print(a2.T)


[[1 5]
 [2 6]]
[[6 3]
 [7 5]]


In [150]:
a3 = np.array([[3,4,5], [7,2,33], [9,1,2], [2,3,33]])
a3

array([[ 3,  4,  5],
       [ 7,  2, 33],
       [ 9,  1,  2],
       [ 2,  3, 33]])

In [140]:
a3[1] [2]

4

In [152]:
a3[3] [2]

33

In [154]:
a3[1:3, 0:2]


array([[7, 2],
       [9, 1]])